on:
  push:
    branches: [ 'main' ]

jobs:
  factions:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew shadowJar
      - name: Deploy project to artifactory
        run: ./gradlew publish
      - name: Deploy project to remote servers
        run: |
          sh /home/cloud/scripts/services/github/actions/deploy.sh build/libs/factions.jar